version: '0.1.{build}'

install:
    - git submodule update --init --recursive

skip_commits:
    message: /NOBUILD.*/

assembly_info:
    patch: true
    file: AssemblyInfo.*
    assembly_version: "{version}"
    assembly_file_version: "{version}"
    assembly_informational_version: "{version}"

build:
    project: HappyGB.sln
