version: '0.1.{build}'

platform:
    - x86

skip_commits:
    message: /NOBUILD.*/

assembly_info:
    patch: true
    file: AssemblyInfo.*
    assembly_version: "{version}"
    assembly_file_version: "{version}"
    assembly_informational_version: "{version}"

install:
    - git submodule update --init --recursive

before_build:
    - nuget restore

build:
    project: HappyGB.sln
